# Generated by Django 5.2.6 on 2026-08-26 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestprofile',
            name='designation',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='home_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='identity_document_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='identity_number',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='identity_type',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='occupation',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='signature_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='workplace',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
