# Generated by Django 5.2.6 on 2026-08-26 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('finance', '0001_initial'),
        ('hotels', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbooking',
            name='folio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_booking', to='finance.folio'),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_bookings', to='hotels.hotel'),
        ),
        migrations.AddField(
            model_name='eventservice',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='events.eventbooking'),
        ),
        migrations.AddField(
            model_name='eventtask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventtask',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='events.eventbooking'),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_types', to='hotels.hotel'),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='events.eventtype'),
        ),
        migrations.AddField(
            model_name='venue',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venues', to='hotels.hotel'),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='events.venue'),
        ),
        migrations.AddConstraint(
            model_name='eventtype',
            constraint=models.UniqueConstraint(fields=('hotel', 'name'), name='unique_hotel_event_type'),
        ),
        migrations.AddConstraint(
            model_name='venue',
            constraint=models.UniqueConstraint(fields=('hotel', 'name'), name='unique_hotel_venue'),
        ),
        migrations.AddIndex(
            model_name='eventbooking',
            index=models.Index(fields=['venue', 'start_at', 'end_at', 'status'], name='events_even_venue_i_6a5c4b_idx'),
        ),
    ]
