# Generated by Django 5.2.6 on 2026-08-26 20:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('icon', models.CharField(blank=True, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('capacity', models.PositiveSmallIntegerField(default=2)),
                ('base_rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('size_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('bed_description', models.CharField(blank=True, max_length=120)),
                ('image_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('amenities', models.ManyToManyField(blank=True, related_name='room_types', to='rooms.amenity')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='hotels.hotel')),
            ],
            options={
                'ordering': ('display_order', 'base_rate'),
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=20)),
                ('floor', models.CharField(blank=True, max_length=30)),
                ('occupancy_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('OCCUPIED', 'Occupied'), ('OUT_OF_SERVICE', 'Out of service')], db_index=True, default='AVAILABLE', max_length=20)),
                ('cleaning_status', models.CharField(choices=[('CLEAN', 'Clean'), ('DIRTY', 'Needs cleaning'), ('IN_PROGRESS', 'Cleaning'), ('INSPECT', 'Awaiting inspection')], db_index=True, default='CLEAN', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotels.hotel')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='rooms.roomtype')),
            ],
            options={
                'ordering': ('number',),
            },
        ),
        migrations.AddConstraint(
            model_name='roomtype',
            constraint=models.UniqueConstraint(fields=('hotel', 'slug'), name='unique_hotel_room_type'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('hotel', 'number'), name='unique_hotel_room_number'),
        ),
    ]
