import {useEffect,useState} from 'react';
import {CalendarDays,Clock3,DoorOpen,ReceiptText,UserRound,WalletCards} from 'lucide-react';
import {Link} from 'react-router-dom';
import {api} from '../../services/api';
import {hotelOps} from '../../services/hotelOperationsService';
import {useAuth} from '../../context/AuthContext';
import {useHotel} from '../../context/HotelContext';

export default function Dashboard(){
  const{user}=useAuth();const{money}=useHotel();const customer=user.role==='CUSTOMER';
  const[bookings,setBookings]=useState([]);const[folios,setFolios]=useState([]);const[events,setEvents]=useState([]);const[summary,setSummary]=useState(null);const[loading,setLoading]=useState(true);
  useEffect(()=>{let active=true;(async()=>{try{if(customer){const[{data},f,e]=await Promise.all([api.get('/bookings/mine/'),hotelOps.folios(),hotelOps.events()]);if(active){setBookings(data.results||data);setFolios(f);setEvents(e)}}else if(['OWNER','ADMIN','MANAGER'].includes(user.role)){const data=await hotelOps.commandCenter();if(active)setSummary(data)}}finally{if(active)setLoading(false)}})();return()=>{active=false}},[customer,user.role]);
  if(!customer)return <div className="mx-auto max-w-7xl"><Welcome user={user} customer={false}/>{loading?<div className="surface-card mt-7 p-8">Loading today’s hotel position…</div>:summary?<div className="mt-7 grid gap-5 md:grid-cols-2 xl:grid-cols-4"><Summary icon={CalendarDays} label="Arrivals today" value={summary.stays?.arrivals_today??0}/><Summary icon={DoorOpen} label="Occupied rooms" value={summary.rooms?.occupied??0}/><Summary icon={Clock3} label="Pending bookings" value={summary.stays?.booking_requests??0}/><Summary icon={WalletCards} label="Open folios" value={summary.finance?.open_folios??0}/></div>:<div className="surface-card mt-7 p-8"><b>{user.role.replaceAll('_',' ')} workspace</b><p className="mt-2 text-sm text-slate-500">Use the permitted sections in the sidebar to complete today’s work.</p></div>}<div className="mt-7 flex flex-wrap gap-3">{['RECEPTIONIST','MANAGER','ADMIN','OWNER'].includes(user.role)&&<Link className="btn-primary" to="/dashboard/reservations">Open reception</Link>}{['MANAGER','ADMIN','OWNER'].includes(user.role)&&<Link className="btn-secondary" to="/dashboard/command-center">View command center</Link>}</div></div>;
  const outstanding=folios.reduce((sum,x)=>sum+Number(x.balance||0),0);
  return <div className="mx-auto max-w-7xl"><Welcome user={user} customer/><div className="mt-7 grid gap-5 md:grid-cols-4"><Summary icon={CalendarDays} label="Booking requests" value={bookings.length}/><Summary icon={Clock3} label="Awaiting confirmation" value={bookings.filter(x=>x.status==='REQUESTED').length}/><Summary icon={ReceiptText} label="Guest folios" value={folios.length}/><Summary icon={WalletCards} label="Outstanding" value={money(outstanding)}/></div><section className="surface-card mt-7 overflow-hidden"><div className="border-b border-slate-100 p-6"><h2 className="font-serif text-2xl">My bookings</h2><p className="body-copy mt-1 text-sm">References and current confirmation status.</p></div>{loading?<p className="p-8 text-slate-500">Loading your hotel account…</p>:bookings.length?<div className="divide-y divide-slate-100">{bookings.map(x=><article key={x.id} className="grid gap-4 p-6 hover:bg-cream/50 md:grid-cols-[1.2fr_1fr_1fr_auto] md:items-center"><div><p className="font-bold">{x.room_type_name}</p><p className="text-xs text-slate-500">{x.reference}</p></div><p className="text-sm">{x.arrival_date} → {x.departure_date}</p><p className="text-sm">{x.guest_name}</p><span className="w-fit rounded-full bg-mist px-3 py-1 text-xs font-bold">{x.status}</span></article>)}</div>:<div className="p-10 text-center"><UserRound className="mx-auto text-slate-300" size={38}/><p className="mt-3 font-bold">No bookings yet</p><p className="body-copy mt-1 text-sm">Your booking requests will appear here.</p></div>}</section>{events.length>0&&<section className="surface-card mt-7 p-6"><h2 className="font-serif text-2xl">My event requests</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{events.map(x=><div className="rounded-2xl bg-cream p-4" key={x.id}><b>{x.title}</b><p className="mt-1 text-sm text-slate-500">{x.reference} · {x.status}</p></div>)}</div></section>}</div>
}
function Welcome({user,customer}){return <div className="rounded-[2rem] bg-gradient-to-br from-forest to-ink p-7 text-white shadow-xl md:p-10"><p className="eyebrow text-gold">Your workspace</p><h1 className="mt-3 font-serif text-4xl md:text-5xl">Good to see you, {user.first_name||'welcome'}.</h1><p className="mt-4 max-w-2xl text-white/65">{customer?'Review your stays, event requests and financial position in one place.':'Your live hotel operations workspace is ready.'}</p>{customer&&<Link to="/book" className="btn-primary mt-7"><CalendarDays size={18}/>Request a booking</Link>}</div>}
function Summary({icon:Icon,label,value}){return <div className="surface-card flex items-center gap-4 p-6"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-mist text-forest"><Icon/></span><div><p className="text-xl font-black">{value}</p><p className="text-sm text-slate-500">{label}</p></div></div>}
