import {Eye,EyeOff,Save} from 'lucide-react';
import {useEffect,useState} from 'react';
import {toast} from 'sonner';
import MediaUpload from '../../components/dashboard/MediaUpload';
import {PageTitle,Panel} from '../../components/dashboard/Panel';
import {useAuth} from '../../context/AuthContext';
import {useHotel} from '../../context/HotelContext';
import {api} from '../../services/api';

export default function Settings(){
  const{user,refreshUser}=useAuth();const{hotel,refreshHotel}=useHotel();const[profile,setProfile]=useState({first_name:user.first_name,last_name:user.last_name,phone:user.phone||'',preferred_language:user.preferred_language||'en'});const[property,setProperty]=useState({...hotel,policies:hotel.policies||{}});const[password,setPassword]=useState({current_password:'',new_password:''});const[show,setShow]=useState(false);const[saving,setSaving]=useState('');const manager=['OWNER','ADMIN'].includes(user.role);
  const updateProfile=async e=>{e.preventDefault();setSaving('profile');try{await api.patch('/auth/me/',profile);await refreshUser();toast.success('Profile updated.')}catch(error){toast.error(error.response?.data?.detail||'Profile could not be updated.')}finally{setSaving('')}};
  const updateHotel=async e=>{e.preventDefault();setSaving('hotel');try{await api.patch('/hotel/settings/',property);await refreshHotel();toast.success('Hotel identity updated throughout the application.')}catch(error){toast.error(error.response?.data?.detail||'Hotel settings could not be updated.')}finally{setSaving('')}};
  const updatePassword=async e=>{e.preventDefault();setSaving('password');try{await api.post('/auth/change-password/',password);setPassword({current_password:'',new_password:''});toast.success('Password updated.')}catch(error){toast.error(error.response?.data?.current_password?.[0]||'Password could not be updated.')}finally{setSaving('')}};
  return <><PageTitle eyebrow="Settings" title="Account and property configuration" copy="Property identity comes from the database; account security remains personal."/><div className="grid gap-6 xl:grid-cols-2"><Panel title="My profile"><form className="grid gap-4" onSubmit={updateProfile}>{['first_name','last_name','phone'].map(key=><Field key={key} label={key.replace('_',' ')} value={profile[key]} onChange={value=>setProfile(x=>({...x,[key]:value}))}/>)}<button disabled={saving==='profile'} className="btn-primary"><Save size={17}/>{saving==='profile'?'Saving…':'Save profile'}</button></form></Panel><Panel title="Change password"><form className="grid gap-4" onSubmit={updatePassword}>{['current_password','new_password'].map(key=><label className="text-sm font-bold" key={key}>{key.replaceAll('_',' ')}<span className="relative mt-2 block"><input required minLength={8} type={show?'text':'password'} className="form-input pr-12" value={password[key]} onChange={e=>setPassword(x=>({...x,[key]:e.target.value}))}/><button type="button" aria-label="Show or hide password" onClick={()=>setShow(x=>!x)} className="absolute right-3 top-1/2 -translate-y-1/2">{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></span></label>)}<button disabled={saving==='password'} className="btn-primary">{saving==='password'?'Updating…':'Update password'}</button></form></Panel>{manager&&<><div className="xl:col-span-2"><StaffAccounts/></div><div className="xl:col-span-2"><Panel title="Hotel identity" copy="These values update the public site and operational documents without source-code edits."><form className="grid gap-4 md:grid-cols-2" onSubmit={updateHotel}>{['name','short_name','phone','email','city','country','currency','timezone'].map(key=><Field key={key} label={key.replaceAll('_',' ')} value={property[key]||''} onChange={value=>setProperty(x=>({...x,[key]:value}))}/>) }<MediaUpload label="Hotel logo" value={property.logo_url} onChange={logo_url=>setProperty(x=>({...x,logo_url}))}/><MediaUpload label="Hero image" value={property.hero_image_url} onChange={hero_image_url=>setProperty(x=>({...x,hero_image_url}))}/><label className="text-sm font-bold md:col-span-2">Description<textarea className="form-input mt-2" rows="4" value={property.description||''} onChange={e=>setProperty(x=>({...x,description:e.target.value}))}/></label><button disabled={saving==='hotel'} className="btn-primary md:col-span-2">{saving==='hotel'?'Saving property…':'Save property settings'}</button></form></Panel></div></>}</div></>
}
function Field({label,value,onChange}){return <label className="text-sm font-bold capitalize">{label}<input required className="form-input mt-2" value={value} onChange={e=>onChange(e.target.value)}/></label>}
function StaffAccounts(){const[staff,setStaff]=useState([]);const[showForm,setShowForm]=useState(false);const[busy,setBusy]=useState(false);const[form,setForm]=useState({email:'',password:'',first_name:'',last_name:'',phone:'',role:'RECEPTIONIST',is_active:true});const load=()=>api.get('/auth/staff/').then(({data})=>setStaff(data.results||data));useEffect(()=>{load()},[]);const submit=async e=>{e.preventDefault();setBusy(true);try{await api.post('/auth/staff/',form);toast.success(`${form.role.toLowerCase()} account created.`);setShowForm(false);setForm({email:'',password:'',first_name:'',last_name:'',phone:'',role:'RECEPTIONIST',is_active:true});load()}catch(error){toast.error(error.response?.data?.email?.[0]||error.response?.data?.password?.[0]||'Staff account could not be created.')}finally{setBusy(false)}};return <Panel title="Staff accounts and roles" copy="Create the manager, receptionist, finance, outlet and operations accounts used by the role-protected dashboard." action={<button className="btn-primary" onClick={()=>setShowForm(x=>!x)}>{showForm?'Close form':'Add staff account'}</button>}>{showForm&&<form className="mb-6 grid gap-4 rounded-2xl bg-cream p-5 md:grid-cols-2" onSubmit={submit}>{['first_name','last_name','email','phone'].map(key=><Field key={key} label={key.replaceAll('_',' ')} value={form[key]} onChange={value=>setForm(x=>({...x,[key]:value}))}/>) }<label className="text-sm font-bold">Role<select className="form-input mt-2" value={form.role} onChange={e=>setForm({...form,role:e.target.value})}>{['MANAGER','RECEPTIONIST','FINANCE','BAR','RESTAURANT','HOUSEKEEPING','EVENTS','MARKETING','EMPLOYEE','ADMIN'].map(role=><option key={role}>{role}</option>)}</select></label><label className="text-sm font-bold">Temporary password<input required minLength={8} className="form-input mt-2" type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label><button disabled={busy} className="btn-primary md:col-span-2">{busy?'Creating account…':'Create staff account'}</button></form>}<div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead><tr><th className="pb-3">Name</th><th>Email</th><th>Role</th><th>Status</th><th>Action</th></tr></thead><tbody>{staff.map(person=><tr className="border-t border-slate-100" key={person.id}><td className="py-4 font-bold">{person.first_name} {person.last_name}</td><td>{person.email}</td><td>{person.role}</td><td>{person.is_active?'Active':'Inactive'}</td><td><button className="text-xs font-bold text-forest" onClick={async()=>{await api.patch(`/auth/staff/${person.id}/`,{is_active:!person.is_active});toast.success('Account status updated.');load()}}>{person.is_active?'Deactivate':'Activate'}</button></td></tr>)}</tbody></table></div></Panel>}
