# Generated by Django 5.2.6 on 2026-08-26 21:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_initial'),
        ('hotels', '0002_initial'),
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=24, unique=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('SETTLED', 'Settled'), ('CLOSED', 'Closed'), ('VOID', 'Void')], db_index=True, default='OPEN', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='folios', to='bookings.guestprofile')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='folios', to='hotels.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='FolioCharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('ROOM', 'Accommodation'), ('OUTLET', 'Outlet'), ('EVENT', 'Event'), ('SERVICE', 'Service'), ('ADJUSTMENT', 'Adjustment')], max_length=16)),
                ('description', models.CharField(max_length=240)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('source_type', models.CharField(blank=True, max_length=60)),
                ('source_id', models.CharField(blank=True, max_length=64)),
                ('is_void', models.BooleanField(default=False)),
                ('void_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_folio_charges', to=settings.AUTH_USER_MODEL)),
                ('folio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='finance.folio')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('PARTIAL', 'Partially paid'), ('PAID', 'Paid'), ('VOID', 'Void')], default='DRAFT', max_length=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_hotel_invoices', to=settings.AUTH_USER_MODEL)),
                ('folio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='finance.folio')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(max_length=30, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('MOBILE_MONEY', 'Mobile money'), ('BANK', 'Bank'), ('CREDIT', 'Credit'), ('OTHER', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', max_length=16)),
                ('provider_reference', models.CharField(blank=True, max_length=120)),
                ('proof_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('received_at', models.DateTimeField()),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('reversal_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('folio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.folio')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_hotel_payments', to=settings.AUTH_USER_MODEL)),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_hotel_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('arrival_date', models.DateField()),
                ('departure_date', models.DateField()),
                ('occupants', models.PositiveSmallIntegerField(default=1)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('RESERVED', 'Reserved'), ('CHECKED_IN', 'Checked in'), ('CHECKED_OUT', 'Checked out'), ('CANCELLED', 'Cancelled')], db_index=True, default='RESERVED', max_length=16)),
                ('vehicle_registration', models.CharField(blank=True, max_length=40)),
                ('vehicle_colour', models.CharField(blank=True, max_length=40)),
                ('purpose_of_visit', models.CharField(blank=True, max_length=160)),
                ('coming_from', models.CharField(blank=True, max_length=160)),
                ('going_to', models.CharField(blank=True, max_length=160)),
                ('account_payer', models.CharField(blank=True, max_length=160)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stay', to='bookings.booking')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stays', to='bookings.guestprofile')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stays', to='hotels.hotel')),
                ('receptionist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_stays', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stays', to='rooms.room')),
            ],
        ),
        migrations.AddField(
            model_name='folio',
            name='stay',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='folio', to='finance.stay'),
        ),
        migrations.AddIndex(
            model_name='stay',
            index=models.Index(fields=['hotel', 'room', 'arrival_date', 'departure_date', 'status'], name='finance_sta_hotel_i_15fe7d_idx'),
        ),
    ]
