import uuid
from django.conf import settings
from django.db import models
from bookings.models import GuestProfile
from hotels.models import Hotel
from rooms.models import Room

class HousekeepingTask(models.Model):
    class Status(models.TextChoices): OPEN='OPEN','Open'; ASSIGNED='ASSIGNED','Assigned'; IN_PROGRESS='IN_PROGRESS','In progress'; INSPECTION='INSPECTION','Inspection'; DONE='DONE','Done'
    id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False); room=models.ForeignKey(Room,on_delete=models.PROTECT,related_name='housekeeping_tasks'); task_type=models.CharField(max_length=60,default='CLEANING'); status=models.CharField(max_length=16,choices=Status.choices,default=Status.OPEN,db_index=True); priority=models.CharField(max_length=12,default='NORMAL'); assigned_to=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.SET_NULL,null=True,blank=True,related_name='housekeeping_tasks'); due_at=models.DateTimeField(null=True,blank=True); notes=models.TextField(blank=True); completed_at=models.DateTimeField(null=True,blank=True); created_at=models.DateTimeField(auto_now_add=True); updated_at=models.DateTimeField(auto_now=True)
class MaintenanceTicket(models.Model):
    class Status(models.TextChoices): REPORTED='REPORTED','Reported'; ASSIGNED='ASSIGNED','Assigned'; IN_PROGRESS='IN_PROGRESS','In progress'; RESOLVED='RESOLVED','Resolved'; CLOSED='CLOSED','Closed'
    id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False); hotel=models.ForeignKey(Hotel,on_delete=models.PROTECT,related_name='maintenance_tickets'); room=models.ForeignKey(Room,on_delete=models.PROTECT,null=True,blank=True,related_name='maintenance_tickets'); title=models.CharField(max_length=180); description=models.TextField(); priority=models.CharField(max_length=12,default='NORMAL'); status=models.CharField(max_length=16,choices=Status.choices,default=Status.REPORTED); reported_by=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.PROTECT,related_name='reported_maintenance'); assigned_to=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.SET_NULL,null=True,blank=True,related_name='assigned_maintenance'); resolution=models.TextField(blank=True); created_at=models.DateTimeField(auto_now_add=True); resolved_at=models.DateTimeField(null=True,blank=True)
class Notification(models.Model):
    id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False); user=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,related_name='hotel_notifications'); title=models.CharField(max_length=160); message=models.TextField(); kind=models.CharField(max_length=40,default='INFO'); action_url=models.CharField(max_length=240,blank=True); is_read=models.BooleanField(default=False); created_at=models.DateTimeField(auto_now_add=True)
class Communication(models.Model):
    class Channel(models.TextChoices): EMAIL='EMAIL','Email'; SMS='SMS','SMS'; WHATSAPP='WHATSAPP','WhatsApp'; PUSH='PUSH','Push'
    class Status(models.TextChoices): QUEUED='QUEUED','Queued'; SENT='SENT','Sent'; DELIVERED='DELIVERED','Delivered'; FAILED='FAILED','Failed'
    id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False); hotel=models.ForeignKey(Hotel,on_delete=models.PROTECT,related_name='communications'); guest=models.ForeignKey(GuestProfile,on_delete=models.SET_NULL,null=True,blank=True,related_name='communications'); channel=models.CharField(max_length=16,choices=Channel.choices); recipient=models.CharField(max_length=180); subject=models.CharField(max_length=180,blank=True); message=models.TextField(); template_key=models.CharField(max_length=80,blank=True); status=models.CharField(max_length=16,choices=Status.choices,default=Status.QUEUED); scheduled_at=models.DateTimeField(null=True,blank=True); sent_at=models.DateTimeField(null=True,blank=True); created_by=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.SET_NULL,null=True,blank=True,related_name='created_communications'); created_at=models.DateTimeField(auto_now_add=True)
class Campaign(models.Model):
    class Status(models.TextChoices): DRAFT='DRAFT','Draft'; SCHEDULED='SCHEDULED','Scheduled'; RUNNING='RUNNING','Running'; COMPLETED='COMPLETED','Completed'; CANCELLED='CANCELLED','Cancelled'
    id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False); hotel=models.ForeignKey(Hotel,on_delete=models.CASCADE,related_name='campaigns'); name=models.CharField(max_length=160); channel=models.CharField(max_length=20); segment=models.JSONField(default=dict,blank=True); offer=models.TextField(blank=True); budget=models.DecimalField(max_digits=12,decimal_places=2,default=0); starts_at=models.DateTimeField(); ends_at=models.DateTimeField(); status=models.CharField(max_length=16,choices=Status.choices,default=Status.DRAFT); acquisition_source=models.CharField(max_length=80,blank=True); created_by=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.PROTECT,related_name='campaigns'); created_at=models.DateTimeField(auto_now_add=True)
class SyncOperation(models.Model):
    class Status(models.TextChoices): PENDING='PENDING','Pending'; PROCESSING='PROCESSING','Processing'; SYNCED='SYNCED','Synced'; FAILED='FAILED','Failed'; CONFLICT='CONFLICT','Conflict'
    id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False); operation_id=models.UUIDField(unique=True); user=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.PROTECT,related_name='sync_operations'); entity_type=models.CharField(max_length=80); operation=models.CharField(max_length=20); payload=models.JSONField(); status=models.CharField(max_length=16,choices=Status.choices,default=Status.PENDING); result=models.JSONField(null=True,blank=True); conflict=models.JSONField(null=True,blank=True); attempts=models.PositiveSmallIntegerField(default=0); created_at=models.DateTimeField(auto_now_add=True); processed_at=models.DateTimeField(null=True,blank=True)
